# Generated by Django 2.0.6 on 2018-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('hacker_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
