CREATE TABLE CONTESTS(CONTEST_ID INT PRIMARY KEY, HACKER_ID INT, NAME VARCHAR(20));

CREATE TABLE COLLEGES(COLLEGE_ID INT PRIMARY KEY, CONTEST_ID INT, FOREIGN KEY(CONTEST_ID) REFERENCES CONTEST(CONTEST_ID));

CREATE TABLE CHALLENGES(CHALLENGE_ID INT PRIMARY KEY, COLLEGE_ID INT, FOREIGN KEY(COLLEGE_ID) REFERENCES COLLEGE(COLLEGE_ID));

CREATE TABLE VIEW_STATS(CHALLENGE_ID INT, TOTAL_VIEWS INT, TOTAL_UNIQUE_VIEWS, FOREIGN KEY(CHALLENGE_ID) REFERENCES CHALLENGE(CHALLENGE_ID));

CREATE TABLE SUBMISSION_STATS(CHALLENGE_ID INT, TOTAL_SUBMISSION INT, TOTAL_ACCEPTED_SUBMISSION INT, FOREIGN KEY(CHALLENGE_ID) REFERENCES CHALLENGES(CHALLENGE_ID));
